### ISSUE TITLE
Some questions related to the reduced GB network in the Pandapower package

### ISSUE THREAD

**Issue by crazystevepotatoes** [e2nIEE/pandapower#1117]
I am currently using the reduced GB network in the Pandapower as a case study for reliability analysis of power grid. I have mainly three questions related to the reduced GB network in the Pandapower.
 
According to the case in Pandapower, the total sum of the generation (active power) is 73714.14 MW while the total load (active power) is 56325.86 MW. However, I also tried using the command “converter.from_ppc” to transfer the same data in Pypower to its corresponding Pandapower format and found that the total generation became 36822.77 MW. Meanwhile, compared to the original Pandapower file, the transferred Pandapower file has more static generators (sgen). I am confused about the difference between the two files which are exactly from the same data source.
I also tried to implement the AC power flow simulation on the original Pandapower file of the reduced GB network. When I used the runpp command, the max loading percent of transmission lines is 181.12%. However, when the runopp command is implemented on the same case the corresponding max loading percent turned out to be 90.79%. I am also confused about the huge difference between the results from the above two ways of AC power flow calculation.
According to the original Pandapower file of the reduced GB network, the total generation is 73714.14 MW and the total load is 56325.86 MW, which is very different from the real-life data provided by the UK national grid (I used the real-life demand data of the UK national grid in year 2019-2020) which shows that the mean value of the real-life demand is actually 36223.96 MW.  I wonder why the total load of the original reduced GB network in the Pandapower has much larger total demand than that in the real-life data and why the total generation is much larger than the total load in the same original Pandapower file. Do I need to rescale the total load and the total generation based on the real-life data before I run AC power flow simulations?
 
I would be very grateful if you could give me some feedbacks on the questions.

**Comment by SteffenMeinecke** [comment]
Dear crazystevepotatoes,

according to your 1st paragraph: As a service for you I attached the .m file received from the [websource](https://www.maths.ed.ac.uk/optenergy/NetworkData/reducedGB/) of the test case and the according .mat file:
[GBreducednetwork.zip](https://github.com/e2nIEE/pandapower/files/5924184/GBreducednetwork.zip)

```
import pandapower as pp
import pandapower.networks as nw
import pandapower.converter as cv
net1 = nw.GBreducednetwork()
net2 = cv.from_mpc("GBreducednetwork/GBreducednetwork.mat")
print(net1)
print(net2)
print(net1.gen.p_mw.sum() + net1.sgen.p_mw.sum())
print(net2.gen.p_mw.sum() + net2.sgen.p_mw.sum())
pp.runpp(net1)
pp.runpp(net2)
```
Using this code you can see that the only difference between the net received from the saved pandapower networks and the net converted from the .mat file is that several generating units are not stored into the gen DataFrame anymore but to the sgen DataFrame. This is a change of the converter which happend without updating the pandapower networks. The change ist due to power flow difficulties which could happen if severel generators are connected to the same bus, espescally with different vm_pu. However, the sum active power of sgens and gens of both nets is 73930.14 MW. Similarly, the power flow results are the same.

According paragraph 2: Of course there is a difference between runpp() and runopp().

According paragraph 3: I am not aware of any real-life data provided by the UK national grid. Either contact the originators of the dataset or scale down the load if you think that makes sense.

**Comment by crazystevepotatoes** [comment]
Thank you!
