### ISSUE TITLE
Missing matplotlib dependency

### ISSUE THREAD

**Issue by jbarberia** [e2nIEE/pandapower#1212]
I clone the repository, set up a fresh virtual environment and ran the tests as follows:

```
python setup.py install
pytest
```

I had 3 errors due to missing matplotlib module.

**Comment by rbolgaryn** [comment]
Hi @jbarberia ,

matplotlib dependency is optional in pandapower, because it is possible that pandapower is used for calculations on a server without a graphical user interface.
A better fix would be to add a try..expect block for matplotlib in the files that rely on it, with a logging message for the user.

**Comment by jbarberia** [comment]
Hello @rbolgaryn ,

Yes there are better ways to fix it. The pull request #1213 was a quick fix.
