### ISSUE TITLE
Full matrix short circuit curent/ fault at different voltage phases

### ISSUE THREAD

**Issue by amjadmouhaidali** [e2nIEE/pandapower#1243]
Dear pandapower team, 
 
I’m quite new to pandapower and I am studying the short circuit current in a network with wind power generators. I found pandapower extremely helpful and the tutorials are very constructive. 
I have some questions about the SC calculations, excuse me if this has already been asked and answered.
Please find the code that I’m running. 
[SC Mouhaidali.txt](https://github.com/e2nIEE/pandapower/files/6565941/SC.Mouhaidali.txt)

1-	How to get the full matrix of ikss and ip (all the currents for all faults). I used the command (returns_all_currents) but I’m having only the max and min. 
2-	I want to test the SC current at different phases of the signal. For example, the fault will occur when the voltage at (0°, 45°,90°,…). I don’t know if the code takes into consideration different phases. I was using EMTP-RV to calculate the SC current, and I found different values depending on the phase of the signal. 
3-	For sources with full converters and in the short circuit conditions, the grid code impose the injection of reactive power to provide a dynamic voltage support. Do you have or planned to implement this feature in your code. 
 
Thank you very much.

**Comment by wangzhenassd** [comment]
Hi @amjadmouhaidali,
to question 1: the result in the net.res_bus_sc is the fault current for the faults at all buses. Is the value you required, the sc current contribution from other buses on the fault on one specific bus? If this is the case, then it is not supported yet but would be a nice enhancement.
to question 2,3: in pandapower we currently support a subset of functionality defined in IEC 60909, in which the SC current can be calculated by the approximate process of equivalent voltage source. The dynamic process, which e.g. required an EMT simulation, during an SC process is hard or impossible to implement for pandapower, since pandapower is more or less a tool focused on power system analysis in static/quasi-static domain.
