### ISSUE TITLE
Can make_PTDF matrix handle islanded networks?

### ISSUE THREAD

**Issue by AnkurArohi** [e2nIEE/pandapower#1577]
Pandapower exception:-

An Error occurred during the computation of sensitivities: Distributed slack calculation is not implemented for several separa
te zones at once, please calculate the zones separately

Lets say we have a network which also has islands, Is it possible for make PTDF to calculate the H matrix ?
Here we are not talking about distributed slack but one slack and multiple zones.

Because with distributed slacks we receive the exception as mentioned above

**Comment by rbolgaryn** [comment]
for the distributed slack calculation, you could adjust the code to implement it also for separate zones (if this would help). 
For that, you would need to add the additional row and additional column for every disconnected zone, rather than once for the whole grid.
You can then open a pull request with this feature.
For PTDF atrix you can try and see if it works with the grid that has separate zones (I am not familiar with the implementation very well).

Best regards,
Roman
