### ISSUE TITLE
[bug] [fileio] Network converted from CIM Scheme showing multiple columns for bus_geodata. Not sure the data issue or grouping issue or both

### ISSUE THREAD

**Issue by AIShankhoGhosh** [e2nIEE/pandapower#1909]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar reports
* [X] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html) 
* [X] Browse the [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for useful code snippets and examples of use

* [X] Reproduced the issue after updating with `pip install --upgrade pandapower` (or `git pull`)
CIM converter not yet in pip install

* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted interpreter
    * [X] Checked the pythonpath
* [x] Completed the **Problem Description**, **What steps reproduce the problem** and **Versions** sections below

## Problem Description

The network data converted from CIM file:
https://connecteddata.nationalgrid.co.uk/dataset/0338c15d-98f8-4d64-ac1c-d95289870898/resource/e014d8b5-3739-45c4-a4e6-7fa63a856be4/download/abham_sgp.zip

There are 66733 Buses but only 53783 in bus_geodata
In the file it can be easily seen that there are multiple columns ( x0,y0,x1,y1....) in addition to x,y data. 

Could this be a data issue or something happened while grouping PositionPoint data ?

### What steps reproduce the problem?

1. Download the dataset
2. Install pandapower from source (Github)
3. Convert CIM file (.zip) using:

` import os 
import pandapower as pp 
from pandapower.converter.cim import * 
cgmes_file2 = r'abham_sgp.zip' 
net2 = from_cim.from_cim(file_list=cgmes_file2) 
pp.to_excel(net2, "example2.xlsx") 
`
### What is the expected output? What do you see instead?
Expected:
Number of buses in the bus and bus_geodata should be same
There should be only x& y data in bus_geodata for each bus
There should be only x0, y0, x1, y1 data in the line_geodata 

What actually is:
There are 66733 Buses in 'bus' but only 53783 in 'bus_geodata' 
There are multiple columns ( x0,y0,x1,y1....) in addition to x,y in bus_geodata and (x0,y0,x1,y1,......) in line_geodata as well. 

### Paste Traceback/Error Below (if applicable)

```

## Versions
pandapower                    2.11.1

* pandas version: 1.3.5
* networkx version: 2.6.3
* scipy version:  1.7.3
* numpy version: 1.21.6
* packaging version: 23.0
* tqdm version: 23.0
* deepdiff version: 6.2.3
* Operating System name/version: Windows 11
* Conda Environment


## Labels (if access available)
* [ ] Choose a `labels` at the right side (e.g. `bug`, `controller`, `OPF`...)

**Comment by AIShankhoGhosh** [comment]
<img width="217" alt="counts" src="https://user-images.githubusercontent.com/127742391/226337912-47d60065-29f4-41f3-ba11-2b0055c38ded.png">
<img width="794" alt="multiple columns" src="https://user-images.githubusercontent.com/127742391/226337916-5b94d0bf-3b5f-4707-83b4-421a3f0d05ad.png">
<img width="685" alt="count_bus" src="https://user-images.githubusercontent.com/127742391/226337920-53e37361-9800-48dc-93a1-f879e4b3fae2.png">

**Comment by mrifraunhofer** [comment]
Hey AIShankhoGhosh, 
this issue is not reproduceable in version 2.13.1. Converting the provided CGMES dataset leads to the following result:
This pandapower network includes the following parameter tables:
   - bus (**13546** element)
   - load (1017 element)
   - sgen (1237 element)
   - gen (12 element)
   - switch (16047 element)
   - shunt (21 element)
   - ext_grid (21 element)
   - line (2319 element)
   - trafo (73 element)
   - trafo3w (80 element)
   - impedance (422 element)
   - ward (875 element)
   - characteristic (446 element)
   - controller (5 element)
   - bus_geodata (**13546** element)
   - characteristic_temp (1917 element)
The number of busses and geodata for busses is equal.

Suggestion: Update pandapower to version 2.13.1

Regarding the columns: Even busses may have more than one x,y coordinate (ie. Busbars). For the lines: No geodata provided in the dataset.

Note: The provided CGMES dataset is not valid! No loadflow possible due to missing data.
