### ISSUE TITLE
How to specify pw_mw for ext_grid

### ISSUE THREAD

**Issue by angrysnail** [e2nIEE/pandapower#2273]
### Feature Checklist

- [X] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar reports

- [ ] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html)

- [ ] Browse the [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for usefull code snippets and examples of use

### Issue

I want to hold a specified value for ext_grid,  by adjusting the pcs, pvs, even the load。 But the load, sgen, storage in pandapower， all need to specify a p_mw value, then after runpp(),  the ext_grid p_mw value will be changed even I set ext_grid's controllable=False.
Any suggestion?

### Label

- [ ] Relevant labels are selected

**Comment by pawellytaev** [comment]
In power flow analysis, the `ext_grid` automatically adjusts to balance the total generation and load in the network, since it acts as an infinite bus. You set a voltage and as a result you get the results P&Q. 
To maintain a specified `ext_grid` value, you need a control strategy that adjusts the power of other elements (loads, PVs, storage) dynamically.
As you can see in the doc for `ext_grid` https://pandapower.readthedocs.io/en/latest/elements/ext_grid.html , the max_p_mw and min_p_mw are only considered in OPF
