### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by AmeliaNadal** [e2nIEE/pandapower#2495]
### Issue

Good morning dear pandapower developers,
Can you maybe release pandapower please? This would be helpful!
The [version](https://github.com/e2nIEE/pandapower/blob/develop/pandapower/_version.py) is incorrect, this could also be adjusted.
Thanks a lot for your attention.

**Comment by KS-HTK** [comment]
The Version in the Develop branch indicates the intended next version. This is required because the tests for the converter can only successfully run if the version has already been updated after the last release. This is required once the develop branch contains any changes that require a change in the format that a network is saved otherwise alot of test will fail.

How would you suggest should the version number incrementation should be handled? How did you come to the conclusion that the number is incorrect? What should the number be?

A Release is planned and currently there are some PRs we are waiting for before a release will be made. There should be a release in the next couple of weeks.
