### ISSUE TITLE
PowerFlow results are unrealistic in diiferent time steps

### ISSUE THREAD

**Issue by frapettob** [e2nIEE/pandapower#452]
Hello everybody,
I have issues regarding my simulations with pandapower. I use pandapower to simulate different scenarios of my electrical grids with time series. I usually do simulations of one day (in 96 time steps). The problem is that with some grids the power results are absolutely unrealistics in some of the timesteps because the Slack-Bus deliveres way more power than the grid needs (for example 40  MW instead of 4 MW). As I said before, these results are not in every timesteps, but mostly they appear in cases of a high power demand. The orginal database of the grids is in NEPLAN and when I do the simulation in NEPLAN there are no issues with the results. 

Has someone an idea what could cause the issue und how I could fix it?

Kind regards,

Tobi

**Comment by lthurner** [comment]
It is hard to know what is going on in this case without seeing the grid. Please run this function in a state where this happens:

```
from pandapower.test.consistency_checks import runpp_with_consistency_checks
runpp_with_consistency_checks(net)
```

This will run a power flow and check internal consistency of the results (if load and generation are balanced etc.). If this function throws an error, there is some issue in the power flow, otherwise the mistake is in the input data.
