### ISSUE TITLE
problem with storage

### ISSUE THREAD

**Issue by Misbahrani** [e2nIEE/pandapower#486]
Hello!
I am trying to implement storage, I selected the following specs:
![image](https://user-images.githubusercontent.com/52325843/63722797-4ff5a580-c86d-11e9-9c98-155861f70472.png)

Initially the soc is zero, and both p_mw & q_mvar is zero, but after running OPF it gives:
![image](https://user-images.githubusercontent.com/52325843/63722543-d2319a00-c86c-11e9-92ee-2deb65b322be.png)
The real_power is discharging
reative_power is charging
how is that possible?
Is there any method to fix that???
i want to use storage for peak shaving, so that it can store energy during off-peak hours and discharge during hours of high-demand
Best regards,
Misbah Rani

**Comment by FlorianShepherd** [comment]
The storage is similar to sgens or loads if you just run a single OPF. The SOC is not taken into account in the OPF.

You have set limits for P (max_p_mw, min_p_mw) and Q (max_q_mvar, min_q_mvar) and also controllable=True. Therefore, the storage P and Q values will be set according to these limits. SOC is *not* considered at all, since it would depend on a step size between two time steps. 

If you want to use it considering the SOC in a time series simulation, you'd have to implement that yourself.
