### ISSUE TITLE
Setup from github does not install matplotlib and plotly

### ISSUE THREAD

**Issue by Svosw** [e2nIEE/pandapower#535]
When installing pandapower via `pip install -e .`, matplotlib and plotly are not installed.

edit: `igraph` is missing as well.

**Comment by lthurner** [comment]
That is intentional because these libraries are not necessary to use pandapower unless you want to do specific plotting tasks. Especially matplotlib and igraph have depencies on C++ libraries an cannot be easily installed through pip on Windows machines. That is why we don't want to make these necessary depencies and potentially block people from being able to install pandapower.

**Comment by FlorianShepherd** [comment]
@SimonRubenDrauz Please add information in documentation about setup with -e

**Comment by dlohmeier** [comment]
I changed the setup.py in PR #642 . It now has an extras_require for plotting including plotly, matplitlib and python-igraph . This can be used by typing pip install -e .[plotting] . Hope that helps.

**Comment by dlohmeier** [comment]
You could even type `pip install -e .[plotting, doc]`
