### ISSUE TITLE
Is there an example of running Short Circuit Sims with case14 network?

### ISSUE THREAD

**Issue by Conet1502** [e2nIEE/pandapower#651]
Is there an example of running Short Circuit Sims with case14 network?

![image](https://user-images.githubusercontent.com/25015389/74046494-e46f4280-498b-11ea-8081-b973f0c44158.png)
![image](https://user-images.githubusercontent.com/25015389/74046528-f3ee8b80-498b-11ea-838e-3326ce5bfab1.png)

**Comment by lthurner** [comment]
You need to add a value for "vn_kv" for the rated voltage of the generator to the net.gen dataframe, since this value is not included in the original IEEE data sets (as far as I know). The documentation lists all parameters that need to be given: https://pandapower.readthedocs.io/en/v2.2.1/elements/gen.html#input-parameters (the parameters with *** are needed, see legend below)
