### ISSUE TITLE
Editing Existing Network

### ISSUE THREAD

**Issue by hectormara** [e2nIEE/pandapower#721]
Is it possible to remove buses in an existing network? 
How can we change the impedance of a line when it has already been created?

**Comment by ascheidl** [comment]
hi, it is just as easy as altering the dataframes of the elements.

that is, for changing the impediance of line 10 just do net.line.loc[10, "r_in_ohm"] = 0.1

However, for dropping buses it is better to use the toolbox function pandapower.drop_buses, since this function also drops all connected elements.

cheers,
alex
