### ISSUE TITLE
Include IEC 60909-4 network for short-circuit calculation

### ISSUE THREAD

**Issue by rwl** [e2nIEE/pandapower#78]
Part 4 of IEC 60909 provides "Examples for the calculation of short-circuit currents". It would be interesting if pandapower included these among the existing collection of example networks:

https://pandapower.readthedocs.io/en/v1.4.1/networks.html

They could be used in the test suite to ensure compliance with the standard. The Conformity Assessment Scheme provides test configurations based on this model (MiniGrid) in CIM RDF/XML format:

https://www.entsoe.eu/Documents/CIM_documents/Grid_Model_CIM/CGMES_v2.4.15_TestConfigurations_v4.0.3.zip

**Comment by lthurner** [comment]
I tested all the short circuit functionality against commercial tools (mostly powerfactory, but also Sincal), which I assume comply with the standard, because that was more convenient and flexible to handle. I agree that having the examples from the standard would be nice, but I currently don't have the time to do it. Of course if you or anyone else what be able to do it, that would be much appreciated.

Since the example grids are quite small, it might be easier to manually create them through the pandapower API than to parse the CIM file provided by ENTSO-E.

**Comment by rwl** [comment]
I have added a test case for the IEC 60909-4, section 6 network here:

https://github.com/rwl/pandapower/commit/334ee18a217e5d5d412bf0d4bb0d161065190507

The results do not match up yet, but most of the input values should be correct.

**Comment by FlorianShepherd** [comment]
Please reopen if there is any update on this @rwl

**Comment by wangzhenassd** [comment]
@rbolgaryn do you think this example would be a good starting point for the generator-close shortcircuit calculation?
