### ISSUE TITLE
Timeseries_example does not compile

### ISSUE THREAD

**Issue by 12o13** [e2nIEE/pandapower#792]
I attempted to run the code from the timeseries_example, as the title shows, but the code does not compile. I have a fix for the code but it is not a complete fix. The fix compiles all but one command, when I attempt to run the ts.run_timeseries command I get "IndexingError: Too many indexers". So I don't know if my fix doesn't acutally work or there is an indexing error in the run_time_series command. I will reference this Issue in the code Push since I cannot upload the .rst file here.

This brings another issue up, the naming conventions throughout the documentation are inconsistent and incomplete. I've tried to push some updates concerning this, and will to go through and fix the rest if thats helpful. I would like some direction on the requested naming conventions, as I am not a primary caretaker of this database.

**Comment by FlorianShepherd** [comment]
You're right that's a mistake. Thank you @12o13 for mentioning this. 

I like your fix but I think it would be nice to add a running example without the need to have *.csv file for loads and sgens. I updated the docs and would integrate it (see commit 28d2a395756c4843466e8795ea6b6c010b3e7a6d). I hope that is ok for you since I don't integrate your commit now. (Btw there's is mistake in line 45 it must be `ds = FrameData.DFData(df)` instead of `ds = Frame.Data.DFData(df)`)
