### ISSUE TITLE
loads behave like generators if negative?

### ISSUE THREAD

**Issue by dkazacos** [e2nIEE/pandapower#809]
I have a "prosumer model" where at each iteration I run a power flow calculation. Prosumers are plugged with "create_load()". After every power flow calculation, the load values for the prosumers are updated. A prosumer is a have PV generators. I model the feed-in as a negative value for the load and positive when demand. The documentation for "Load" says _If you want to model constant generation, use a Static Generator (sgen element) instead of a negative load_
The "create_load()" _OPTIONAL_ argument _p_mw_ says _negative value -> generation_

It is not clear for me which element to use. Does the update of the p_mw in the load element make sense in my case?

**Comment by FlorianShepherd** [comment]
You can use loads with negative values as generators in power flow calculations. It's just not a very nice style. If you can, rather use `sgen` instead of a `negative load` when you want to model generation. 

In your case this should be fine. Maybe consider having both elements at the same bus. One for generation (sgen) one for consumption (load)

Background:
Both elements, loads and sgens, are converted to "PQ"-nodes internally. This means that if you use a positive value for sgens the value is negative in the bus-branch-model. Vice versa you'll get a negative value for the PQ-bus where your load is attached to if net.load.p_mw is negative. From the "powerflows' perspective" there is no difference. Looking at the results its "strange" to have negative loads. Also, this can be a problem in other calculations, e.g., when using the OPF.
